### ISSUE TITLE
Issues with commands `fold prep_name` and vacuity with `assume pred_name` 

### ISSUE THREAD

**Issue by nrp364** [nyu-acsys/raven#17]
I am seeing the following error frequently when folding predicates: `Internal Error: Expected inv function call (e/own).`

I am also seeing a vacuity being introduced after `assume pred_name;` command (where I believe it shouldn't).

To reproduce: checkout `nisarg/issue-fold-assume`, run `dune exec -- raven test/comparison/lclist.rav`. See lines [40-78](https://github.com/nyu-acsys/raven/blob/f61084be90423840463a66f672310a86a15ff3c0/test/comparison/lclist.rav#L40) in `test/comparison/lclist.rav`.

**Comment by EkanshdeepGupta** [comment]
The first bug is fixed here: ac3543a4686159f52831b78aafade03879ce7818
